### ISSUE TITLE
Main loop implementation

### ISSUE THREAD

**Issue by arturmalecki** [kwojn/ultimateSlayer#1]
Hi,

Using `window.setInterval` for game loop is not a great idea. You can kill browser with this :)

Please consider this https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame

https://hacks.mozilla.org/2011/08/animating-with-javascript-from-setinterval-to-requestanimationframe/

**Comment by kwojn** [comment]
Confirmed. I will change it. Thanks a lot.
