### ISSUE TITLE
Sugestie

### ISSUE THREAD

**Issue by kskrzypkowski** [kwojn/ultimateSlayer#2]
Dodaj namierzanie i strzelanie myszką.
Popraw animacje strzału (najpierw strzała leci a potem cięciwa jest naciągana) 
Przydały by się animacje trafienia.
Skakanie spacją

**Comment by kwojn** [comment]
Animacja strzału poprawiona.

**Comment by kwojn** [comment]
Celowanie myszką zrobine
Animacja trafienia zrobiona

**Comment by kwojn** [comment]
Skakanie spacja :) Zamykam
